application: sched-up
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- deferred: on
- appstats: on

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: schedup.main.app

inbound_services:
- mail

libraries:
- name: webob
  version: latest
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: endpoints
  version: latest
- name: pycrypto
  version: "latest"

